-- Migration number: 0001 	 2025-01-12T06:50:08.546Z
CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY UNIQUE NOT NULL,
  prefer_dark_mode BOOLEAN DEFAULT FALSE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS message (
  id TEXT PRIMARY KEY UNIQUE NOT NULL,
  user_id TEXT,
  text TEXT,
  role TEXT,
  thread_id TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id),
  FOREIGN KEY (thread_id) REFERENCES threads(id)
);

CREATE TABLE IF NOT EXISTS threads (
  id TEXT PRIMARY KEY UNIQUE NOT NULL,
  user_id TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  title TEXT,
  FOREIGN KEY (user_id) REFERENCES users(id)
);
