export const config = {
  __PRIVATE__: {
    MAX_TEXT_INPUT_LENGTH: 10000,
    MAX_PASSWORD_LENGTH: 100,
    MAX_USERNAME_LENGTH: 100,
    MAX_EMAIL_LENGTH: 255,
    MAX_SECRET_QUESTION_LENGTH: 1000,
  },
  AUTH_CHECK_INTERVAL: 1000 * 20, // 1 minute
};
