/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignUpImport } from './routes/sign-up'
import { Route as SecurityQuestionsImport } from './routes/security-questions'
import { Route as MeImport } from './routes/me'
import { Route as LoginImport } from './routes/login'
import { Route as ForgotPasswordImport } from './routes/forgot-password'
import { Route as DebugImport } from './routes/debug'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as IndexImport } from './routes/index'
import { Route as DocumentsIndexImport } from './routes/documents/index'
import { Route as DocumentsIdImport } from './routes/documents/$id'

// Create/Update Routes

const SignUpRoute = SignUpImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRoute,
} as any)

const SecurityQuestionsRoute = SecurityQuestionsImport.update({
  id: '/security-questions',
  path: '/security-questions',
  getParentRoute: () => rootRoute,
} as any)

const MeRoute = MeImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const ForgotPasswordRoute = ForgotPasswordImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRoute,
} as any)

const DebugRoute = DebugImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DocumentsIndexRoute = DocumentsIndexImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => rootRoute,
} as any)

const DocumentsIdRoute = DocumentsIdImport.update({
  id: '/documents/$id',
  path: '/documents/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugImport
      parentRoute: typeof rootRoute
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeImport
      parentRoute: typeof rootRoute
    }
    '/security-questions': {
      id: '/security-questions'
      path: '/security-questions'
      fullPath: '/security-questions'
      preLoaderRoute: typeof SecurityQuestionsImport
      parentRoute: typeof rootRoute
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpImport
      parentRoute: typeof rootRoute
    }
    '/documents/$id': {
      id: '/documents/$id'
      path: '/documents/$id'
      fullPath: '/documents/$id'
      preLoaderRoute: typeof DocumentsIdImport
      parentRoute: typeof rootRoute
    }
    '/documents/': {
      id: '/documents/'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/debug': typeof DebugRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/security-questions': typeof SecurityQuestionsRoute
  '/sign-up': typeof SignUpRoute
  '/documents/$id': typeof DocumentsIdRoute
  '/documents': typeof DocumentsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/debug': typeof DebugRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/security-questions': typeof SecurityQuestionsRoute
  '/sign-up': typeof SignUpRoute
  '/documents/$id': typeof DocumentsIdRoute
  '/documents': typeof DocumentsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/debug': typeof DebugRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/security-questions': typeof SecurityQuestionsRoute
  '/sign-up': typeof SignUpRoute
  '/documents/$id': typeof DocumentsIdRoute
  '/documents/': typeof DocumentsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/debug'
    | '/forgot-password'
    | '/login'
    | '/me'
    | '/security-questions'
    | '/sign-up'
    | '/documents/$id'
    | '/documents'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/debug'
    | '/forgot-password'
    | '/login'
    | '/me'
    | '/security-questions'
    | '/sign-up'
    | '/documents/$id'
    | '/documents'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/debug'
    | '/forgot-password'
    | '/login'
    | '/me'
    | '/security-questions'
    | '/sign-up'
    | '/documents/$id'
    | '/documents/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DebugRoute: typeof DebugRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MeRoute: typeof MeRoute
  SecurityQuestionsRoute: typeof SecurityQuestionsRoute
  SignUpRoute: typeof SignUpRoute
  DocumentsIdRoute: typeof DocumentsIdRoute
  DocumentsIndexRoute: typeof DocumentsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DebugRoute: DebugRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MeRoute: MeRoute,
  SecurityQuestionsRoute: SecurityQuestionsRoute,
  SignUpRoute: SignUpRoute,
  DocumentsIdRoute: DocumentsIdRoute,
  DocumentsIndexRoute: DocumentsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dashboard",
        "/debug",
        "/forgot-password",
        "/login",
        "/me",
        "/security-questions",
        "/sign-up",
        "/documents/$id",
        "/documents/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.tsx"
    },
    "/debug": {
      "filePath": "debug.tsx"
    },
    "/forgot-password": {
      "filePath": "forgot-password.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/me": {
      "filePath": "me.tsx"
    },
    "/security-questions": {
      "filePath": "security-questions.tsx"
    },
    "/sign-up": {
      "filePath": "sign-up.tsx"
    },
    "/documents/$id": {
      "filePath": "documents/$id.tsx"
    },
    "/documents/": {
      "filePath": "documents/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
