/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignUpImport } from './routes/sign-up'
import { Route as SecurityQuestionsImport } from './routes/security-questions'
import { Route as PageImport } from './routes/page'
import { Route as MeImport } from './routes/me'
import { Route as LoginImport } from './routes/login'
import { Route as ForgotPasswordImport } from './routes/forgot-password'
import { Route as ErrorImport } from './routes/error'
import { Route as DebugImport } from './routes/debug'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as IndexImport } from './routes/index'
import { Route as AppTransactionsIndexImport } from './routes/app/transactions/index'
import { Route as AppTransactionsNewImport } from './routes/app/transactions/new'

// Create/Update Routes

const SignUpRoute = SignUpImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRoute,
} as any)

const SecurityQuestionsRoute = SecurityQuestionsImport.update({
  id: '/security-questions',
  path: '/security-questions',
  getParentRoute: () => rootRoute,
} as any)

const PageRoute = PageImport.update({
  id: '/page',
  path: '/page',
  getParentRoute: () => rootRoute,
} as any)

const MeRoute = MeImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const ForgotPasswordRoute = ForgotPasswordImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRoute,
} as any)

const ErrorRoute = ErrorImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRoute,
} as any)

const DebugRoute = DebugImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AppTransactionsIndexRoute = AppTransactionsIndexImport.update({
  id: '/app/transactions/',
  path: '/app/transactions/',
  getParentRoute: () => rootRoute,
} as any)

const AppTransactionsNewRoute = AppTransactionsNewImport.update({
  id: '/app/transactions/new',
  path: '/app/transactions/new',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugImport
      parentRoute: typeof rootRoute
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorImport
      parentRoute: typeof rootRoute
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeImport
      parentRoute: typeof rootRoute
    }
    '/page': {
      id: '/page'
      path: '/page'
      fullPath: '/page'
      preLoaderRoute: typeof PageImport
      parentRoute: typeof rootRoute
    }
    '/security-questions': {
      id: '/security-questions'
      path: '/security-questions'
      fullPath: '/security-questions'
      preLoaderRoute: typeof SecurityQuestionsImport
      parentRoute: typeof rootRoute
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpImport
      parentRoute: typeof rootRoute
    }
    '/app/transactions/new': {
      id: '/app/transactions/new'
      path: '/app/transactions/new'
      fullPath: '/app/transactions/new'
      preLoaderRoute: typeof AppTransactionsNewImport
      parentRoute: typeof rootRoute
    }
    '/app/transactions/': {
      id: '/app/transactions/'
      path: '/app/transactions'
      fullPath: '/app/transactions'
      preLoaderRoute: typeof AppTransactionsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/debug': typeof DebugRoute
  '/error': typeof ErrorRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/page': typeof PageRoute
  '/security-questions': typeof SecurityQuestionsRoute
  '/sign-up': typeof SignUpRoute
  '/app/transactions/new': typeof AppTransactionsNewRoute
  '/app/transactions': typeof AppTransactionsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/debug': typeof DebugRoute
  '/error': typeof ErrorRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/page': typeof PageRoute
  '/security-questions': typeof SecurityQuestionsRoute
  '/sign-up': typeof SignUpRoute
  '/app/transactions/new': typeof AppTransactionsNewRoute
  '/app/transactions': typeof AppTransactionsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/debug': typeof DebugRoute
  '/error': typeof ErrorRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/page': typeof PageRoute
  '/security-questions': typeof SecurityQuestionsRoute
  '/sign-up': typeof SignUpRoute
  '/app/transactions/new': typeof AppTransactionsNewRoute
  '/app/transactions/': typeof AppTransactionsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/debug'
    | '/error'
    | '/forgot-password'
    | '/login'
    | '/me'
    | '/page'
    | '/security-questions'
    | '/sign-up'
    | '/app/transactions/new'
    | '/app/transactions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/debug'
    | '/error'
    | '/forgot-password'
    | '/login'
    | '/me'
    | '/page'
    | '/security-questions'
    | '/sign-up'
    | '/app/transactions/new'
    | '/app/transactions'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/debug'
    | '/error'
    | '/forgot-password'
    | '/login'
    | '/me'
    | '/page'
    | '/security-questions'
    | '/sign-up'
    | '/app/transactions/new'
    | '/app/transactions/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DebugRoute: typeof DebugRoute
  ErrorRoute: typeof ErrorRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MeRoute: typeof MeRoute
  PageRoute: typeof PageRoute
  SecurityQuestionsRoute: typeof SecurityQuestionsRoute
  SignUpRoute: typeof SignUpRoute
  AppTransactionsNewRoute: typeof AppTransactionsNewRoute
  AppTransactionsIndexRoute: typeof AppTransactionsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DebugRoute: DebugRoute,
  ErrorRoute: ErrorRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MeRoute: MeRoute,
  PageRoute: PageRoute,
  SecurityQuestionsRoute: SecurityQuestionsRoute,
  SignUpRoute: SignUpRoute,
  AppTransactionsNewRoute: AppTransactionsNewRoute,
  AppTransactionsIndexRoute: AppTransactionsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dashboard",
        "/debug",
        "/error",
        "/forgot-password",
        "/login",
        "/me",
        "/page",
        "/security-questions",
        "/sign-up",
        "/app/transactions/new",
        "/app/transactions/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.tsx"
    },
    "/debug": {
      "filePath": "debug.tsx"
    },
    "/error": {
      "filePath": "error.tsx"
    },
    "/forgot-password": {
      "filePath": "forgot-password.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/me": {
      "filePath": "me.tsx"
    },
    "/page": {
      "filePath": "page.tsx"
    },
    "/security-questions": {
      "filePath": "security-questions.tsx"
    },
    "/sign-up": {
      "filePath": "sign-up.tsx"
    },
    "/app/transactions/new": {
      "filePath": "app/transactions/new.tsx"
    },
    "/app/transactions/": {
      "filePath": "app/transactions/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
