// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.778
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"bus.zcauldron.com/pkg/views/partials"
)

// SEE PARTIALS ALSO
// pkg/views/partials/ReceiptConfirmation.templ
// pkg/views/partials/ReceiptManualEdit.templ

type ReceiptUploadFormData struct {
	Title      string
	IsLoggedIn bool
}

func ReceiptUploadForm(data ReceiptUploadFormData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html lang=\"en\"><head>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = partials.GlobalHead(data.Title).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<style>\n        .zc-or-manual-upload-container {\n            margin-top: 20px;\n            margin-right: auto;\n            margin-left: auto;\n            display: flex;\n            justify-content: flex-end;\n            align-items: flex-end;\n        }\n\n        .zc-manual-upload-button {\n            width: fit-content;\n        }\n      </style></head><body>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = partials.GlobalHeader(data.IsLoggedIn).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<main><div class=\"message-container\"><i class=\"fa-solid fa-triangle-exclamation\"></i><p id=\"message\">Your viewing a deprecated version of the finance history page. Please use the new version. <a href=\"/dashboard/finances/v2/receipts\">Click here to go to the new version.</a></p></div><div id=\"zc-receipt-upload\"><form class=\"receipt-upload-container\" id=\"imageUploadForm\" enctype=\"multipart/form-data\" hx-post=\"/upload\" hx-target=\"#zc-receipt-upload\" hx-swap=\"outerHTML\" hx-trigger=\"submit\" hx-indicator=\"#loading-spinner\" hx-on:submit=\"sessionStorage.removeItem(&#39;zc-temp-receipt&#39;);\"><h2>Upload Receipt</h2><label for=\"image\">Drag and drop your receipt image here, or click to select a file</label> <input id=\"zc-receipt-upload\" type=\"file\" id=\"image\" name=\"image\" accept=\"image/*\" required> <span class=\"info-text\">Supported file types: .png, .jpeg, .jpg, .webp, .gif</span> <button type=\"submit\" class=\"primary-button\">Upload</button><div id=\"loading-spinner\" class=\"htmx-indicator pulse-indicator\">Processing your request. This may take a few moments...</div></form><div class=\"zc-or-manual-upload-container\"><button type=\"button\" class=\"secondary-button zc-manual-upload-button\" id=\"manual-upload-button\" hx-get=\"/manual-upload\" hx-target=\"#zc-receipt-upload\" hx-swap=\"outerHTML\" hx-trigger=\"click\" hx-on:click=\"sessionStorage.removeItem(&#39;zc-temp-receipt&#39;);\">Manual Upload</button></div></div></main>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = partials.GlobalFooter().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<script src=\"/js/receipt-utils.js\"></script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
