export const PROMPTS = {
  "For Writers and Content Creators": [
    "Write a short story about a time-traveling detective.",
    "Generate a blog post outlining the future of renewable energy.",
    "Create a dialogue between two characters from different centuries.",
    "Develop a character sketch for a hero with an unusual superpower.",
    "Draft a poem inspired by the quiet of a snowy evening.",
    "Outline a feature article on the impact of social media on creativity.",
    "Write a first-person narrative from the perspective of an ancient artifact.",
    "Create a back-story for a villain that makes the audience sympathize with them.",
    "Compose a review of a fictional book that hasn't been written yet.",
  ],
  "AI Prompt Examples for Marketing": [
    "Craft an engaging product description for an eco-friendly water bottle.",
    "Develop a catchy tagline for a new line of sustainable athletic wear.",
    "Generate a list of SEO keywords for a digital marketing agency.",
    "Create a compelling email subject line for a holiday sale.",
    "Write a script for a 30-second radio ad promoting a new restaurant.",
    "Design a social media campaign for a virtual reality travel company.",
    "Write a press release for a groundbreaking, eco-friendly technology.",
    "Develop a unique selling proposition for a freelancer's portfolio website.",
    "Craft an infographic script explaining the benefits of blockchain for businesses.",
    "Create a user testimonial for a futuristic smart home device.",
  ],
  "For Artists and Designers": [
    "Generate an idea for a mural that celebrates community diversity.",
    "Describe a futuristic cityscape for an AI-generated image.",
    "Provide a prompt for a piece of abstract art that explores the theme of 'connection.'",
    "Create a character concept for a graphic novel set in a post-apocalyptic world.",
    "Suggest a landscape scene for an AI to generate featuring a hidden waterfall.",
    "Generate a concept for a fashion line inspired by underwater ecosystems.",
    "Describe a piece of jewelry that represents a historical era.",
    "Provide inspiration for a sculpture that incorporates elements of wind and movement.",
    "Invent a character design for a video game set in outer space.",
    "Suggest a theme for a photo series that captures the essence of solitude.",
  ],
  "For Developers and Coders": [
    "Generate a list of potential features for a new social media platform.",
    "Create a code snippet for a Python script that automates data analysis.",
    "Develop a prompt for an AI to generate a website layout.",
    "Suggest a prompt for a React component that displays a weather forecast.",
    "Generate a prompt for a SQL query to analyze user engagement data.",
    "Create a prompt for a JavaScript function that validates email addresses.",
    "Develop a prompt for an AI to generate a mobile app interface.",
    "Suggest a prompt for a Python script that scrapes news articles.",
    "Generate a prompt for a React component that displays a list of products.",
  ],
  "For Product Managers": [
    "Generate a list of potential features for a new social media platform.",
    "Create a code snippet for a Python script that automates data analysis.",
    "Develop a prompt for an AI to generate a website layout.",
    "Suggest a prompt for a React component that displays a weather forecast.",
    "Generate a prompt for a SQL query to analyze user engagement data.",
  ],
  "For Marketers": [
    "Generate a list of potential features for a new social media platform.",
    "Create a code snippet for a Python script that automates data analysis.",
    "Develop a prompt for an AI to generate a website layout.",
    "Suggest a prompt for a React component that displays a weather forecast.",
    "Generate a prompt for a SQL query to analyze user engagement data.",
  ],
  "For Sales": [
    "Generate a list of potential features for a new social media platform.",
    "Create a code snippet for a Python script that automates data analysis.",
    "Develop a prompt for an AI to generate a website layout.",
    "Suggest a prompt for a React component that displays a weather forecast.",
    "Generate a prompt for a SQL query to analyze user engagement data.",
  ],
  "For HR": [
    "Generate a list of potential features for a new social media platform.",
    "Create a code snippet for a Python script that automates data analysis.",
    "Develop a prompt for an AI to generate a website layout.",
    "Suggest a prompt for a React component that displays a weather forecast.",
    "Generate a prompt for a SQL query to analyze user engagement data.",
  ],
  "For Designers": [
    "Generate a list of potential features for a new social media platform.",
    "Create a code snippet for a Python script that automates data analysis.",
    "Develop a prompt for an AI to generate a website layout.",
    "Suggest a prompt for a React component that displays a weather forecast.",
    "Generate a prompt for a SQL query to analyze user engagement data.",
  ],
  "For Engineers": [
    "Generate a list of potential features for a new social media platform.",
    "Create a code snippet for a Python script that automates data analysis.",
    "Develop a prompt for an AI to generate a website layout.",
    "Suggest a prompt for a React component that displays a weather forecast.",
    "Generate a prompt for a SQL query to analyze user engagement data.",
  ],
};
